# -*- coding: utf-8 -*-
"""CustomerSegmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QljD5AaiNkGRh7GTdMnPJL8SQaxS_tMO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

customer_data=pd.read_csv('/content/Mall_Customers (1).csv')

customer_data.head()

customer_data.shape

customer_data.isnull().sum()

customer_data.info()

customer_data.describe()

X=customer_data.iloc[:,[3,4]].values

print(X)

"""WCSS-> within cluster sum of squares"""

#finding the number of cluster
wcss=[]
for i in range(1,21):
  k_means=KMeans(n_clusters=i,init='k-means++',random_state=42)
  k_means.fit(X)
  wcss.append(k_means.inertia_)

#plotting the elbow graph
sns.set()
plt.plot(range(1,21),wcss)
plt.title('The Elbow Point Graph')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

"""K=5"""

#Training the model
k_means=KMeans(n_clusters=5,init='k-means++',random_state=0)

#predicting the labels
Y=k_means.fit_predict(X)
print(Y)

"""Visualizing the clusters"""

plt.figure(figsize=(6,6))
plt.scatter(X[Y==0,0],X[Y==0,1],s=50,c='Green',label='Cluster 1')
plt.scatter(X[Y==1,0],X[Y==1,1],s=50,c='Red',label='Cluster 2')
plt.scatter(X[Y==2,0],X[Y==2,1],s=50,c='Blue',label='Cluster 3')
plt.scatter(X[Y==3,0],X[Y==3,1],s=50,c='Yellow',label='Cluster 4')
plt.scatter(X[Y==4,0],X[Y==4,1],s=50,c='Pink',label='Cluster 5')

plt.scatter(k_means.cluster_centers_[:,0],k_means.cluster_centers_[:,1],s=100,c='Black',label='Centroids')

plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()

